version: "3.9"

services:
  client:
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - go_backend

  go_backend:
    build: ./go
    depends_on:
      - redis
    deploy:
      replicas: ${GO_REPLICAS:-1}

  redis:
    image: redis
    restart: always